/**
 * Metadados de todos os inputs: rótulo, unidade, faixa plausível, casas decimais
 * e tooltip com a definição da variável e a fonte do default.
 *
 * A chave é o caminho (dot-path) dentro do objeto Scenario. Este registro é a
 * fonte única usada pela UI, pelos solvers de equilíbrio, pelo gráfico tornado
 * e pela simulação de Monte Carlo.
 */
export type FieldKind = "num" | "pct" | "money" | "bool" | "select" | "text";

export interface FieldMeta {
  label: string;
  unit: string;
  tip: string;
  kind: FieldKind;
  min?: number;
  max?: number;
  dec?: number;
  options?: { value: string; label: string }[];
  /** Marcado como candidato natural a análise de sensibilidade. */
  sens?: boolean;
}

const n = (
  label: string,
  unit: string,
  min: number,
  max: number,
  tip: string,
  dec = 2,
  sens = false,
): FieldMeta => ({ label, unit, min, max, tip, dec, kind: "num", sens });

const m = (
  label: string,
  min: number,
  max: number,
  tip: string,
  sens = false,
): FieldMeta => ({ label, unit: "R$", min, max, tip, dec: 0, kind: "money", sens });

const p = (
  label: string,
  min: number,
  max: number,
  tip: string,
  dec = 1,
  sens = false,
): FieldMeta => ({ label, unit: "%", min, max, tip, dec, kind: "pct", sens });

const b = (label: string, tip: string): FieldMeta => ({
  label,
  unit: "",
  tip,
  kind: "bool",
});

const s = (
  label: string,
  options: { value: string; label: string }[],
  tip: string,
): FieldMeta => ({ label, unit: "", tip, kind: "select", options });

const t = (label: string, tip: string): FieldMeta => ({
  label,
  unit: "",
  tip,
  kind: "text",
});

export const FIELDS: Record<string, FieldMeta> = {
  // ── META ────────────────────────────────────────────────────────────────
  "meta.nome": t("Nome do cenário", "Identificação usada ao salvar e comparar cenários."),
  "meta.autor": t("Autor", "Responsável pelas premissas adotadas."),
  "meta.data": t("Data-base", "Data de referência dos preços informados."),
  "meta.sensiveis": t("Variáveis de sensibilidade", "Lista de campos marcados para entrar no gráfico tornado e nos solvers."),
  "meta.mc": t("Distribuições de Monte Carlo", "Distribuições declaradas para os inputs incertos."),
  "meta.notas": t("Notas", "Observações livres, exportadas no relatório."),

  // ── MISSÃO: perfil operacional ──────────────────────────────────────────
  "mission.horizonteAnos": n("Horizonte de análise", "anos", 1, 25, "Período sobre o qual o VPL do TCO é calculado. Default 10 anos, alinhado ao ciclo típico de renovação de frota pesada.", 0, true),
  "mission.kmAno": n("Quilometragem anual", "km/ano", 5000, 400000, "Distância percorrida por veículo por ano na missão de referência. Base de todos os custos variáveis. Default 100.000 km/ano (perfil rodoviário CNT).", 0, true),
  "mission.diasOperacionaisAno": n("Dias operacionais", "dias/ano", 100, 365, "Dias em que o veículo está disponível para operar. Base do cálculo de disponibilidade.", 0),
  "mission.jornadasDia": n("Jornadas por dia", "jornadas", 1, 3, "Número de turnos operacionais por dia.", 0),
  "mission.horasOperacaoDia": n("Horas de operação", "h/dia", 1, 24, "Horas de calendário operacional por dia, usadas no denominador da disponibilidade.", 1),
  "mission.velocidadeMediaKmH": n("Velocidade operacional média", "km/h", 10, 90, "Velocidade média porta-a-porta, incluindo paradas. Define quantos km cada veículo consegue rodar por ano e, portanto, a frota equivalente. Estimativa de engenharia.", 0),
  "mission.perfilUrbanoPct": p("Perfil urbano", 0, 100, "Percentual da quilometragem em ciclo urbano. Os três perfis devem somar 100%.", 0),
  "mission.perfilRegionalPct": p("Perfil regional", 0, 100, "Percentual da quilometragem em ciclo regional/distribuição.", 0),
  "mission.perfilRodoviarioPct": p("Perfil rodoviário", 0, 100, "Percentual da quilometragem em rodovia de longo curso.", 0),
  "mission.topoPlanoPct": p("Topografia plana", 0, 100, "Percentual do trajeto em terreno plano. Os três perfis somam 100%.", 0),
  "mission.topoOnduladoPct": p("Topografia ondulada", 0, 100, "Percentual do trajeto em terreno ondulado.", 0),
  "mission.topoMontanhosoPct": p("Topografia montanhosa", 0, 100, "Percentual do trajeto em terreno montanhoso.", 0),
  "mission.fatorTopoPlano": n("Fator de consumo — plano", "x", 0.8, 1.5, "Multiplicador do consumo específico em terreno plano (referência = 1,00).", 3),
  "mission.fatorTopoOndulado": n("Fator de consumo — ondulado", "x", 0.8, 1.6, "Multiplicador do consumo em terreno ondulado. Default 1,08 (estimativa de engenharia).", 3),
  "mission.fatorTopoMontanhoso": n("Fator de consumo — montanhoso", "x", 0.8, 2, "Multiplicador do consumo em terreno montanhoso. Default 1,20 (estimativa de engenharia).", 3),
  "mission.distanciaMediaViagemKm": n("Distância média por viagem", "km", 10, 3000, "Extensão típica de uma viagem completa. Usada para dimensionar autonomia e eventos de abastecimento.", 0),
  "mission.distanciaMaxEntrePontosKm": n("Distância máxima entre pontos de abastecimento", "km", 10, 2000, "Trecho mais longo sem ponto de reabastecimento ou recarga. É o teste que a autonomia degradada precisa passar.", 0, true),
  "mission.cargaUtilMediaT": n("Carga útil média transportada", "t", 1, 60, "Massa média de carga por viagem carregada, antes do fator de ocupação.", 1, true),
  "mission.fatorOcupacaoPct": p("Fator de ocupação de carga", 10, 100, "Percentual da carga média efetivamente utilizado. Multiplica a carga útil média para chegar à carga-alvo.", 0),
  "mission.retornoVazioPct": p("Retorno vazio", 0, 90, "Percentual da quilometragem rodada sem carga. Reduz a tonelada-quilômetro produtiva sem reduzir o consumo proporcionalmente.", 0),
  "mission.temperaturaMediaC": n("Temperatura ambiente média", "°C", -5, 45, "Temperatura média de operação. Afeta o consumo do BEV (climatização e condicionamento do pack) e a taxa de degradação da bateria.", 0),
  "mission.ptoPotenciaKW": n("Tomada de força / refrigeração", "kW médio", 0, 60, "Potência média demandada por tomada de força ou refrigeração de carga.", 1),
  "mission.ptoHorasDia": n("Horas de uso da tomada de força", "h/dia", 0, 24, "Horas diárias de uso do PTO ou da refrigeração.", 1),
  "mission.energiaRodaKWhKm": n("Energia na roda de referência", "kWh/km", 0.3, 3, "Energia mecânica necessária na roda, medida no peso bruto de referência, em terreno plano e ciclo rodoviário. O motor a escala por topografia, perfil de rota e peso bruto real de cada configuração. Serve de referência para o balanço energético e para o alerta de eficiência implícita (estimativa de engenharia).", 3),
  "mission.pesoBrutoReferenciaT": n("Peso bruto de referência", "t", 5, 80, "Peso bruto combinado ao qual a energia na roda de referência se refere. Deve ser coerente com a tara mais a carga de referência declarada nas abas das rotas, porque a energia na roda escala linearmente com o peso bruto efetivo.", 1),
  "mission.fatorRodaUrbano": n("Fator de energia na roda — urbano", "x", 0.8, 2.5, "Acréscimo de energia na roda no ciclo urbano, por acelerações e paradas. Estimativa de engenharia.", 2),
  "mission.fatorRodaRegional": n("Fator de energia na roda — regional", "x", 0.8, 2.5, "Acréscimo de energia na roda no ciclo regional. Estimativa de engenharia.", 2),
  "mission.fatorRodaRodoviario": n("Fator de energia na roda — rodoviário", "x", 0.8, 2.5, "Referência do ciclo rodoviário, normalmente 1,00.", 2),
  "mission.aplicarPenalidadePayload": b("Aplicar penalidade de payload", "Quando ativo, rotas com menor carga útil precisam rodar mais quilômetros para mover a mesma tonelagem, e todos os custos variáveis crescem na mesma proporção."),

  // ── MISSÃO: economia ────────────────────────────────────────────────────
  "econ.wacc": p("Taxa de desconto real (WACC)", 0, 40, "Custo de capital real da empresa, líquido de inflação. Default 12% a.a.", 2, true),
  "econ.ipca": p("Inflação geral (IPCA)", 0, 30, "Inflação projetada. Usada apenas para converter a apresentação entre valores reais e nominais — o VPL é invariante.", 2),
  "econ.escDiesel": p("Escalonamento real do diesel", -10, 15, "Variação real do preço do diesel, em % a.a. acima do IPCA.", 2, true),
  "econ.escArla": p("Escalonamento real do ARLA", -10, 15, "Variação real do preço do ARLA 32, % a.a. acima do IPCA.", 2),
  "econ.escGnv": p("Escalonamento real do gás natural", -15, 15, "Variação real do preço do gás natural, % a.a. acima do IPCA.", 2, true),
  "econ.escBio": p("Escalonamento real do biometano", -15, 15, "Variação real do preço do biometano. Default negativo, refletindo o ganho de escala esperado da produção nacional.", 2, true),
  "econ.escEnergia": p("Escalonamento real da energia", -10, 15, "Variação real da tarifa de energia elétrica, % a.a. acima do IPCA.", 2, true),
  "econ.escH2": p("Escalonamento real do H₂", -20, 15, "Variação real do preço do hidrogênio, % a.a. acima do IPCA. Default -3% a.a., refletindo a curva de aprendizado esperada.", 2, true),
  "econ.escMaoObra": p("Escalonamento real da mão de obra", -10, 15, "Ganho real de salários acima do IPCA.", 2),
  "econ.escPecas": p("Escalonamento real de peças", -10, 15, "Variação real do custo de peças e serviços.", 2),
  "econ.escCarbono": p("Escalonamento real do carbono", -10, 30, "Crescimento real do preço do carbono ao longo do horizonte.", 2),
  "econ.usdBrl": n("Câmbio USD/BRL", "R$/US$", 1, 15, "Usado para converter insumos cotados em dólar (CAPEX importado, custo do pack).", 3),
  "econ.eurBrl": n("Câmbio EUR/BRL", "R$/€", 1, 15, "Usado para converter insumos cotados em euro.", 3),
  "econ.baseValores": s("Base de cálculo", [{ value: "real", label: "Valores reais (deflacionados)" }, { value: "nominal", label: "Valores nominais" }], "Define apenas como o fluxo de caixa é apresentado. Na base nominal os valores são inflacionados pelo IPCA e descontados pelo WACC nominal, o que preserva o VPL."),
  "econ.regime": s("Regime de aquisição", [{ value: "avista", label: "Compra à vista" }, { value: "financiamento", label: "Financiamento" }, { value: "leasing", label: "Leasing operacional" }, { value: "aluguel", label: "Aluguel mensal" }], "Compra à vista lança o CAPEX inteiro no ano 0. Financiamento e leasing lançam entrada e prestações. Aluguel substitui CAPEX e depreciação por uma mensalidade."),

  // ── MISSÃO: financiamento ───────────────────────────────────────────────
  "fin.entradaPct": p("Entrada", 0, 100, "Percentual do valor do bem pago no ato.", 1),
  "fin.prazoMeses": n("Prazo", "meses", 6, 180, "Prazo total do financiamento.", 0),
  "fin.carenciaMeses": n("Carência", "meses", 0, 36, "Período inicial em que apenas os juros são pagos.", 0),
  "fin.sistema": s("Sistema de amortização", [{ value: "PRICE", label: "Price (prestação constante)" }, { value: "SAC", label: "SAC (amortização constante)" }], "Define o perfil das prestações. O SAC concentra o desembolso no início e reduz o total de juros pagos."),
  "fin.iofPct": p("IOF", 0, 5, "IOF incidente sobre a operação de crédito, somado ao valor financiado.", 2),
  "fin.estruturacaoPct": p("Custos de estruturação", 0, 8, "Tarifas, cadastro e estruturação, em % do valor financiado.", 2),
  "fin.jurosDiesel": p("Juros — Diesel", 0, 40, "Taxa anual da linha usada para o veículo diesel. Referência: Finame convencional ou CDC bancário.", 2, true),
  "fin.jurosH2": p("Juros — Hidrogênio", 0, 40, "Taxa anual da linha usada para o FCEV. Referência: BNDES Finame Baixo Carbono.", 2, true),
  "fin.jurosBev": p("Juros — Elétrico", 0, 40, "Taxa anual da linha usada para o BEV. Referência: BNDES Finame Baixo Carbono.", 2, true),
  "fin.aluguelMensalDiesel": m("Aluguel mensal — Diesel", 0, 200000, "Mensalidade no regime de aluguel/locação, quando aplicável."),
  "fin.aluguelMensalH2": m("Aluguel mensal — Hidrogênio", 0, 400000, "Mensalidade no regime de aluguel/locação, quando aplicável."),
  "fin.aluguelMensalBev": m("Aluguel mensal — Elétrico", 0, 400000, "Mensalidade no regime de aluguel/locação, quando aplicável."),

  // ── MISSÃO: tributos ────────────────────────────────────────────────────
  "trib.regime": s("Regime tributário", [{ value: "lucroReal", label: "Lucro Real" }, { value: "lucroPresumido", label: "Lucro Presumido" }, { value: "simples", label: "Simples Nacional" }], "Somente no Lucro Real a depreciação e as despesas geram benefício fiscal e há aproveitamento de créditos de PIS/COFINS."),
  "trib.aliquotaIRCSLL": p("IRPJ + CSLL", 0, 50, "Alíquota combinada usada para calcular o benefício fiscal da depreciação, dos juros e das despesas dedutíveis. Default 34% (IRPJ 25% + CSLL 9%).", 1),
  "trib.deduzirDespesasOperacionais": b("Deduzir despesas operacionais", "No Lucro Real, combustível, manutenção e mão de obra são dedutíveis e geram economia de IRPJ/CSLL. Desmarque para ver o TCO antes do efeito tributário sobre o custeio, mantendo apenas o benefício da depreciação e dos juros."),
  "trib.pisCofinsRecupera": b("Recuperar créditos de PIS/COFINS", "Quando ativo, os créditos incidentes sobre combustível, energia e insumos são deduzidos do custo."),
  "trib.pisCofinsCombustivelPct": p("PIS/COFINS — combustíveis", 0, 20, "Alíquota efetiva de crédito sobre diesel, ARLA e hidrogênio.", 2),
  "trib.pisCofinsEnergiaPct": p("PIS/COFINS — energia", 0, 20, "Alíquota efetiva de crédito sobre energia elétrica.", 2),
  "trib.icmsEnergiaPct": p("ICMS sobre energia", 0, 40, "Alíquota de ICMS embutida na tarifa de energia elétrica.", 1),
  "trib.icmsH2Pct": p("ICMS sobre hidrogênio", 0, 40, "Alíquota de ICMS sobre o hidrogênio adquirido.", 1),
  "trib.depAnosDiesel": n("Depreciação fiscal — Diesel", "anos", 1, 25, "Prazo de depreciação fiscal do veículo. Referência: IN RFB 1.700/2017, veículos de carga.", 0),
  "trib.depAnosH2": n("Depreciação fiscal — Hidrogênio", "anos", 1, 25, "Prazo de depreciação fiscal do FCEV e da infraestrutura associada.", 0),
  "trib.depAnosBev": n("Depreciação fiscal — Elétrico", "anos", 1, 25, "Prazo de depreciação fiscal do BEV e da infraestrutura de recarga.", 0),
  "trib.ipvaPctDiesel": p("IPVA — Diesel", 0, 6, "Percentual do valor venal. Caminhões são isentos na maior parte dos estados, por isso o default é zero.", 2),
  "trib.ipvaPctH2": p("IPVA — Hidrogênio", 0, 6, "Percentual do valor venal, já considerando isenções para veículos de emissão zero."),
  "trib.ipvaPctBev": p("IPVA — Elétrico", 0, 6, "Percentual do valor venal, já considerando isenções para veículos de emissão zero."),
  "trib.incentivoCapexPctDiesel": p("Incentivo sobre CAPEX — Diesel", 0, 60, "Crédito ou subvenção como percentual do CAPEX (Rota 2030, MOVER, incentivos estaduais)."),
  "trib.incentivoCapexPctH2": p("Incentivo sobre CAPEX — Hidrogênio", 0, 60, "Crédito sobre o CAPEX: PHBC (Lei 14.948/2024), REHIDRO, isenções estaduais."),
  "trib.incentivoCapexPctBev": p("Incentivo sobre CAPEX — Elétrico", 0, 60, "Crédito sobre o CAPEX: MOVER, Rota 2030, isenções estaduais."),
  "trib.incentivoAnualDiesel": m("Incentivo anual — Diesel", 0, 2000000, "Crédito fiscal recorrente, em R$/ano por veículo."),
  "trib.incentivoAnualH2": m("Incentivo anual — Hidrogênio", 0, 2000000, "Crédito fiscal recorrente, em R$/ano por veículo (PHBC, REHIDRO)."),
  "trib.incentivoAnualBev": m("Incentivo anual — Elétrico", 0, 2000000, "Crédito fiscal recorrente, em R$/ano por veículo."),

  // ── MISSÃO: carbono ─────────────────────────────────────────────────────
  "carbono.fatorDieselKgL": n("Fator de emissão do diesel", "kgCO₂e/L", 1.5, 4.5, "Emissão por litro queimado. O default de 3,17 informado pelo usuário já embute margem de upstream; o TTW puro do diesel B0 fica entre 2,60 e 2,68 kgCO₂/L. Se usar o valor TTW puro, informe o upstream no campo seguinte.", 3, true),
  "carbono.fatorDieselUpstreamKgL": n("Upstream do diesel", "kgCO₂e/L", 0, 2, "Emissões de extração, refino e distribuição. Some 0,50 a 0,60 kgCO₂e/L se o fator anterior for TTW puro. Default zero para não haver dupla contagem.", 3),
  "carbono.fatorEletricidadeKgKWh": n("Fator de emissão da eletricidade", "kgCO₂e/kWh", 0, 1, "Fator médio do SIN brasileiro. Default 0,12 (média histórica MCTI). Contratos I-REC ou PPA renovável zeram este fator.", 3, true),
  "carbono.energiaRenovavelIREC": b("Energia 100% renovável (I-REC/PPA)", "Quando ativo, zera o fator de emissão da eletricidade consumida pelo BEV e pela eletrólise."),
  "carbono.rotaH2": s("Rota de produção do H₂", [{ value: "eletriseGrid", label: "Eletrólise com energia da rede" }, { value: "eletroliseRenovavel", label: "Eletrólise com renovável" }, { value: "biomassa", label: "Biomassa / looping químico" }, { value: "smr", label: "Reforma a vapor (SMR)" }], "Define o fator de emissão do hidrogênio consumido. Só afeta emissões e custo de carbono, não o preço do H₂."),
  "carbono.fatorH2GridKgKg": n("Fator do H₂ — eletrólise com rede", "kgCO₂e/kgH₂", 0, 30, "Consumo específico da eletrólise multiplicado pelo fator da rede. Default 6,5 (52 kWh/kg × 0,125 kgCO₂/kWh).", 2),
  "carbono.fatorH2RenovavelKgKg": n("Fator do H₂ — eletrólise renovável", "kgCO₂e/kgH₂", 0, 10, "Pegada residual de fabricação de equipamentos e balanço de planta. Estimativa de engenharia.", 2),
  "carbono.fatorH2BiomassaKgKg": n("Fator do H₂ — biomassa/looping", "kgCO₂e/kgH₂", -30, 10, "Pode ser negativo quando há captura e estocagem do CO₂ biogênico (BECCS). Estimativa de engenharia.", 2),
  "carbono.fatorH2SmrKgKg": n("Fator do H₂ — SMR", "kgCO₂e/kgH₂", 0, 30, "Reforma a vapor de gás natural sem captura.", 2),
  "carbono.cenarioCarbono": s("Cenário de preço do carbono", [{ value: "zero", label: "Sem preço de carbono" }, { value: "voluntario", label: "Mercado voluntário" }, { value: "sbce", label: "SBCE (Lei 15.042/2024)" }, { value: "cbam", label: "CBAM / EU ETS" }], "Seleciona qual dos preços abaixo é aplicado às emissões."),
  "carbono.precoCarbonoZero": m("Preço do carbono — cenário zero", 0, 0, "Cenário sem precificação. Mantido em zero por definição."),
  "carbono.precoCarbonoVoluntario": n("Preço do carbono — voluntário", "R$/tCO₂e", 0, 1000, "Faixa típica do mercado voluntário brasileiro.", 0, true),
  "carbono.precoCarbonoSbce": n("Preço do carbono — SBCE", "R$/tCO₂e", 0, 1500, "Estimativa de partida do Sistema Brasileiro de Comércio de Emissões (Lei 15.042/2024).", 0, true),
  "carbono.precoCarbonoCbam": n("Preço do carbono — CBAM", "R$/tCO₂e", 0, 2000, "Referência do EU ETS convertida, aplicável a cadeias exportadoras.", 0, true),
  "carbono.cbioElegivel": b("Elegível a CBIOs (RenovaBio)", "Quando aplicável, gera receita adicional de créditos de descarbonização."),
  "carbono.cbioPreco": n("Preço do CBIO", "R$/CBIO", 0, 500, "Cotação do crédito de descarbonização.", 0),
  "carbono.cbioPorAnoBio": n("CBIOs — biometano", "CBIO/ano", 0, 5000, "Quantidade anual atribuível ao veículo movido a biometano. Os CBIOs são emitidos ao produtor do biocombustível; informe aqui a parcela do valor que a frota efetivamente captura no contrato.", 0),
  "carbono.cbioPorAnoH2": n("CBIOs — hidrogênio", "CBIO/ano", 0, 5000, "Quantidade anual atribuível ao veículo a hidrogênio, quando a rota de produção for elegível.", 0),
  "carbono.noxDieselGkm": n("NOx — Diesel", "g/km", 0, 10, "Emissão de óxidos de nitrogênio. Referência: limite Proconve P8.", 3),
  "carbono.mpDieselGkm": n("Material particulado — Diesel", "g/km", 0, 1, "Emissão de MP do escapamento (não inclui desgaste de pneus e freios).", 4),
  "carbono.noxH2Gkm": n("NOx — Hidrogênio", "g/km", 0, 10, "Zero no escapamento para célula a combustível.", 3),
  "carbono.mpH2Gkm": n("Material particulado — Hidrogênio", "g/km", 0, 1, "Zero no escapamento.", 4),
  "carbono.noxBevGkm": n("NOx — Elétrico", "g/km", 0, 10, "Zero no escapamento.", 3),
  "carbono.mpBevGkm": n("Material particulado — Elétrico", "g/km", 0, 1, "Zero no escapamento.", 4),

  // ── MISSÃO: custos comuns ───────────────────────────────────────────────
  "comuns.salarioMotoristaMes": m("Salário do motorista", 0, 30000, "Salário base mensal."),
  "comuns.encargosPct": p("Encargos sobre a folha", 0, 150, "Encargos sociais e provisões, em % do salário.", 1),
  "comuns.beneficiosMes": m("Benefícios", 0, 10000, "Alimentação, saúde e demais benefícios mensais."),
  "comuns.motoristasPorVeiculo": n("Motoristas por veículo", "motoristas", 0, 3, "Relação motorista/veículo, incluindo cobertura de férias e afastamentos.", 2),
  "comuns.treinamentoDiesel": m("Treinamento — Diesel", 0, 50000, "Custo único de treinamento por motorista."),
  "comuns.treinamentoH2": m("Treinamento — Hidrogênio", 0, 50000, "Custo único de capacitação para manuseio de hidrogênio e abastecimento a alta pressão."),
  "comuns.treinamentoBev": m("Treinamento — Elétrico", 0, 50000, "Custo único de capacitação para condução eficiente e segurança em alta tensão."),
  "comuns.seguroPctDiesel": p("Seguro — Diesel", 0, 15, "Prêmio anual como percentual do valor do ativo.", 2, true),
  "comuns.seguroPctH2": p("Seguro — Hidrogênio", 0, 15, "Prêmio anual em % do ativo. Tende a ser maior pelo valor do bem e pela menor experiência atuarial.", 2, true),
  "comuns.seguroPctBev": p("Seguro — Elétrico", 0, 15, "Prêmio anual em % do ativo. Tende a ser maior pelo custo de reparo do pack.", 2, true),
  "comuns.telemetriaMes": m("Rastreamento e telemetria", 0, 5000, "Mensalidade por veículo."),
  "comuns.licenciamentoAno": m("Licenciamento, RNTRC e taxas", 0, 20000, "Custos anuais obrigatórios por veículo."),
  "comuns.pedagioPorKm": n("Pedágio", "R$/km", 0, 3, "Custo médio de pedágio por quilômetro rodado, já ponderado por eixo.", 3),
  "comuns.adminGaragemMes": m("Administrativo e garagem", 0, 20000, "Rateio de estrutura administrativa e de pátio, por veículo por mês."),
  "comuns.custoDiaParado": m("Custo de indisponibilidade", 0, 30000, "Margem de contribuição perdida por dia de veículo parado. Converte tempo de recarga, abastecimento e manutenção em custo."),
  "comuns.pneusQtd": n("Quantidade de pneus", "un", 4, 40, "Total de pneus do conjunto.", 0),
  "comuns.pneuPreco": m("Preço do pneu", 0, 20000, "Preço unitário do pneu novo."),
  "comuns.pneuVidaKm": n("Vida do pneu", "km", 20000, 400000, "Vida do pneu novo na rota diesel de referência. Cada rota aplica seu fator de vida.", 0),
  "comuns.recapagens": n("Recapagens por carcaça", "un", 0, 5, "Número de recapagens aproveitadas por carcaça.", 0),
  "comuns.recapagemCusto": m("Custo da recapagem", 0, 10000, "Custo unitário da recapagem."),
  "comuns.freiosCusto": m("Custo do jogo de freios", 0, 50000, "Custo do conjunto de pastilhas/lonas do veículo."),
  "comuns.freiosVidaKm": n("Vida dos freios", "km", 20000, 500000, "Vida na rota diesel de referência; cada rota aplica seu fator.", 0),
};

// ── DIESEL ────────────────────────────────────────────────────────────────
Object.assign(FIELDS, {
  "diesel.precoAquisicao": m("Preço de aquisição", 0, 5000000, "Preço do conjunto com impostos. Default: cavalo mecânico 6x2, 460 cv, Proconve P8 (referência de mercado 2026).", true),
  "diesel.precoSemImpostos": m("Preço sem impostos", 0, 5000000, "Valor líquido de ICMS/IPI, base para créditos quando aplicável."),
  "diesel.configuracao": s("Configuração", [{ value: "4x2", label: "4x2" }, { value: "6x2", label: "6x2" }, { value: "6x4", label: "6x4" }], "Configuração de tração do cavalo mecânico."),
  "diesel.pbtcT": n("PBTC legal", "t", 10, 100, "Peso bruto total combinado permitido para a configuração. Base do cálculo de carga útil.", 1),
  "diesel.taraBaseT": n("Tara base (sem sistema de energia)", "t", 5, 30, "Massa do conjunto sem tanques, pós-tratamento, pilha ou pack. Permite comparar as três rotas sobre a mesma base.", 2),
  "diesel.potenciaCv": n("Potência", "cv", 100, 800, "Potência nominal do motor.", 0),
  "diesel.norma": s("Norma de emissões", [{ value: "P7", label: "Proconve P7" }, { value: "P8", label: "Proconve P8" }], "P8 exige SCR com maior consumo de ARLA e adiciona custos de pós-tratamento."),
  "diesel.vidaUtilAnos": n("Vida útil operacional", "anos", 1, 25, "Vida econômica considerada para o ativo.", 0),
  "diesel.precoDieselL": n("Preço do diesel S10", "R$/L", 1, 20, "Preço na bomba, com impostos. Referência ANP.", 3, true),
  "diesel.precoDieselSemImpostosL": n("Preço do diesel sem impostos", "R$/L", 0.5, 20, "Base para o cálculo de créditos de PIS/COFINS.", 3),
  "diesel.usarBasePropria": b("Compra em base própria", "Aplica o desconto de compra direta em volume ao preço do diesel."),
  "diesel.descontoBasePropriaPct": p("Desconto da base própria", 0, 30, "Desconto obtido na compra direta em volume.", 1),
  "diesel.consumoUrbanoKmL": n("Consumo — urbano", "km/L", 0.5, 10, "Autonomia em ciclo urbano, carregado na carga de referência.", 2, true),
  "diesel.consumoRegionalKmL": n("Consumo — regional", "km/L", 0.5, 10, "Autonomia em ciclo regional.", 2, true),
  "diesel.consumoRodoviarioKmL": n("Consumo — rodoviário", "km/L", 0.5, 10, "Autonomia em rodovia de longo curso.", 2, true),
  "diesel.cargaReferenciaT": n("Carga de referência do consumo", "t", 0, 50, "Carga transportada à qual os consumos declarados se referem."),
  "diesel.ajusteConsumoPorTonPct": p("Ajuste de consumo por tonelada", 0, 10, "Aumento percentual do consumo por tonelada acima da carga de referência.", 2),
  "diesel.pctMarchaLenta": p("Tempo em marcha lenta", 0, 60, "Percentual das horas de operação com o motor em marcha lenta.", 1),
  "diesel.consumoMarchaLentaLh": n("Consumo em marcha lenta", "L/h", 0, 10, "Consumo horário com o veículo parado e motor ligado.", 2),
  "diesel.perdasEvaporacaoPct": p("Perdas de evaporação e furto", 0, 10, "Percentual do volume abastecido perdido antes do consumo.", 2),
  "diesel.capacidadeTanqueL": n("Capacidade do tanque", "L", 100, 2000, "Volume total de diesel embarcado. Define eventos de abastecimento e massa.", 0),
  "diesel.massaTanqueVazioKg": n("Massa do tanque vazio", "kg", 0, 500, "Massa do próprio tanque, somada ao combustível para compor o sistema de energia.", 0),
  "diesel.posTratamentoMassaKg": n("Massa do pós-tratamento", "kg", 0, 600, "SCR, DPF, silencioso e tubulações.", 0),
  "diesel.tempoAbastecimentoMin": n("Tempo de abastecimento", "min/evento", 1, 120, "Tempo total por evento, incluindo deslocamento e fila.", 0),
  "diesel.eficienciaMotor": n("Eficiência do motor", "fração", 0.2, 0.5, "Eficiência térmica média usada no PTO e no balanço energético. Faixa aceitável 30%–45%.", 3),
  "diesel.arlaMetodo": s("Método de entrada do ARLA", [{ value: "pctDiesel", label: "% do consumo de diesel" }, { value: "litros100km", label: "L/100 km" }], "Escolha a forma como a frota mede o consumo de ARLA 32."),
  "diesel.arlaPctDiesel": p("Consumo de ARLA", 0, 15, "Consumo de ARLA como percentual do volume de diesel. Faixa típica 3% a 8%; motores P8 tendem ao topo da faixa.", 2, true),
  "diesel.arlaL100km": n("Consumo de ARLA", "L/100 km", 0, 20, "Alternativa de entrada, para frotas que medem em litros por 100 km.", 2),
  "diesel.arlaPrecoL": n("Preço do ARLA 32", "R$/L", 0.5, 15, "Preço de compra do ARLA 32.", 2, true),
  "diesel.arlaEventosAno": n("Eventos de contaminação do ARLA", "eventos/ano", 0, 5, "Frequência de contaminação ou cristalização que exige intervenção.", 2),
  "diesel.arlaCustoEvento": m("Custo por evento de contaminação", 0, 50000, "Limpeza de linha, troca de bomba dosadora e mão de obra."),
  "diesel.arlaTanqueL": n("Capacidade do tanque de ARLA", "L", 0, 300, "Volume do tanque de ARLA; entra na tara do veículo.", 0),
  "diesel.oleoVolumeL": n("Óleo de motor — volume", "L", 0, 100, "Volume por troca."),
  "diesel.oleoPrecoL": n("Óleo de motor — preço", "R$/L", 0, 200, "Preço do lubrificante."),
  "diesel.oleoIntervaloKm": n("Óleo de motor — intervalo", "km", 5000, 200000, "Intervalo entre trocas.", 0),
  "diesel.outrosFluidosPctOleo": p("Outros lubrificantes", 0, 200, "Câmbio, diferencial e graxas, como percentual do custo do óleo de motor.", 0),
  "diesel.preventivaPorKm": n("Manutenção preventiva", "R$/km", 0, 3, "Custo de manutenção programada por quilômetro, excluindo itens detalhados separadamente.", 3, true),
  "diesel.filtrosCusto": m("Filtros — custo", 0, 10000, "Ar, combustível e separador de água, por troca."),
  "diesel.filtrosIntervaloKm": n("Filtros — intervalo", "km", 5000, 200000, "Intervalo entre substituições.", 0),
  "diesel.scrCusto": m("Catalisador SCR — custo", 0, 200000, "Substituição do catalisador do sistema de redução seletiva."),
  "diesel.scrVidaKm": n("Catalisador SCR — vida", "km", 100000, 3000000, "Quilometragem até a substituição.", 0),
  "diesel.dpfCusto": m("DPF — limpeza/regeneração", 0, 100000, "Custo por intervenção de limpeza do filtro de particulados."),
  "diesel.dpfIntervaloKm": n("DPF — intervalo", "km", 20000, 1000000, "Intervalo entre limpezas.", 0),
  "diesel.sensorNoxCusto": m("Sensores de NOx — custo", 0, 50000, "Substituição do par de sensores."),
  "diesel.sensorNoxVidaKm": n("Sensores de NOx — vida", "km", 50000, 1000000, "Quilometragem até a falha típica.", 0),
  "diesel.deratingProbAno": n("Probabilidade de derating", "eventos/ano", 0, 5, "Frequência de redução forçada de potência por falha do sistema de emissões.", 2),
  "diesel.deratingCusto": m("Custo por evento de derating", 0, 100000, "Diagnóstico, reparo e parada associada."),
  "diesel.corretivaAno1": m("Corretiva no primeiro ano", 0, 200000, "Manutenção não programada no ano 1; cresce com a idade pela taxa abaixo."),
  "diesel.corretivaCrescimentoPctAA": p("Crescimento da corretiva", 0, 60, "Crescimento anual composto do custo de manutenção corretiva.", 1),
  "diesel.fatorVidaPneu": n("Fator de vida do pneu", "x", 0.5, 1.5, "Multiplicador da vida do pneu em relação à referência. 1,00 para o diesel.", 3),
  "diesel.fatorVidaFreio": n("Fator de vida do freio", "x", 0.5, 4, "Multiplicador da vida do freio em relação à referência. 1,00 para o diesel.", 3),
  "diesel.altoValorCusto": m("Itens de alto valor — custo", 0, 300000, "Embreagem, retarder e sistema de arrefecimento."),
  "diesel.altoValorVidaKm": n("Itens de alto valor — vida", "km", 100000, 3000000, "Quilometragem até a intervenção.", 0),
  "diesel.horasParadoManutAno": n("Horas paradas em manutenção", "h/ano", 0, 2000, "Tempo anual de veículo indisponível por manutenção programada.", 0),
  "diesel.falhaProbAno": n("Panes não programadas", "eventos/ano", 0, 10, "Frequência de falhas que imobilizam o veículo.", 2),
  "diesel.falhaHorasEvento": n("Duração da pane", "h/evento", 0, 200, "Tempo médio de imobilização por pane.", 0),
  "diesel.zonaRestritaPctRotas": p("Rotas afetadas por zona de baixa emissão", 0, 100, "Percentual das rotas sujeitas a restrição de acesso ao longo do horizonte.", 1),
  "diesel.zonaRestritaCustoPct": p("Custo adicional nas rotas restritas", 0, 100, "Acréscimo de custo (desvio, transbordo, terceirização) nas rotas afetadas.", 1),
  "diesel.choqueResidualPct": p("Choque no valor residual", 0, 100, "Desvalorização adicional do ativo no ano final, por obsolescência regulatória.", 1),
  "diesel.descontoReceitaPct": p("Desconto exigido por clientes", 0, 30, "Perda de receita exigida por embarcadores que demandam transporte descarbonizado.", 2),
  "diesel.receitaAnual": m("Receita anual do veículo", 0, 10000000, "Base sobre a qual o desconto exigido é aplicado."),
});

// ── HIDROGÊNIO ────────────────────────────────────────────────────────────
Object.assign(FIELDS, {
  "h2.modoPreco": s("Origem do preço do veículo", [{ value: "direto", label: "Preço direto em R$" }, { value: "importacao", label: "Calcular pela importação" }], "No modo importação o preço é montado a partir do FOB em dólar, frete, seguro, II, IPI, ICMS e despacho."),
  "h2.precoAquisicao": m("Preço de aquisição", 0, 20000000, "Preço do FCEV pesado entregue. Estimativa 2026 para veículo importado com ex-tarifário.", true),
  "h2.precoSemImpostos": m("Preço sem impostos", 0, 20000000, "Valor líquido, base de créditos quando aplicável."),
  "h2.impFobUsd": n("FOB", "US$", 0, 3000000, "Valor FOB do veículo na origem.", 0),
  "h2.impFreteSeguroPct": p("Frete e seguro internacional", 0, 40, "Percentual sobre o FOB para chegar ao CIF.", 1),
  "h2.impIiPct": p("Imposto de Importação", 0, 60, "Alíquota do II. Zero quando há ex-tarifário concedido."),
  "h2.impIpiPct": p("IPI", 0, 40, "Alíquota de IPI na importação."),
  "h2.impIcmsPct": p("ICMS na importação", 0, 40, "Alíquota de ICMS do estado de desembaraço."),
  "h2.impDespachoPct": p("Despacho e armazenagem", 0, 20, "Custos de desembaraço, armazenagem e transporte interno, em % do CIF."),
  "h2.potenciaPilhaKW": n("Potência da pilha", "kW", 30, 500, "Potência nominal da célula a combustível.", 0),
  "h2.bateriaTampaoKWh": n("Bateria tampão — energia", "kWh", 0, 400, "Capacidade da bateria de amortecimento de transientes.", 0),
  "h2.bateriaTampaoKW": n("Bateria tampão — potência", "kW", 0, 800, "Potência de pico entregue pela bateria tampão.", 0),
  "h2.massaPilhaKgPorKW": n("Massa específica da pilha", "kg/kW", 0.5, 6, "Massa do sistema de célula a combustível por kW instalado, incluindo BoP.", 2),
  "h2.massaCilindroKgPorKgH2": n("Massa dos cilindros", "kg/kgH₂", 5, 40, "Massa total do sistema de armazenamento por quilo de hidrogênio estocado, já incluindo o próprio hidrogênio. Tanques tipo IV a 350 bar com suportes ficam entre 16 e 20 kg/kg.", 1),
  "h2.massaBateriaKgPorKWh": n("Massa da bateria tampão", "kg/kWh", 2, 15, "Massa específica do pack tampão.", 2),
  "h2.capacidadeH2Kg": n("Capacidade de H₂ embarcada", "kg", 5, 200, "Massa de hidrogênio armazenada a bordo.", 1, true),
  "h2.pressaoBar": s("Pressão de armazenamento", [{ value: "350", label: "350 bar" }, { value: "700", label: "700 bar" }], "Define a densidade do armazenamento e o custo de compressão na estação."),
  "h2.autonomiaNominalKm": n("Autonomia nominal", "km", 100, 1500, "Autonomia declarada pelo fabricante. A autonomia real é recalculada pelo consumo ajustado.", 0),
  "h2.taraBaseT": n("Tara base (sem sistema de energia)", "t", 5, 30, "Massa do conjunto sem pilha, cilindros e bateria tampão.", 2),
  "h2.pbtcT": n("PBTC legal", "t", 10, 100, "Peso bruto total combinado permitido.", 1),
  "h2.toleranciaRegulatoriaT": n("Tolerância regulatória de peso", "t", 0, 3, "Tolerância adicional de PBTC concedida a veículos de emissão zero. Default zero; informe 1 a 2 t se a legislação aplicável conceder.", 2, true),
  "h2.vidaUtilAnos": n("Vida útil operacional", "anos", 1, 25, "Vida econômica considerada.", 0),
  "h2.consumoUrbanoKg100km": n("Consumo — urbano", "kg H₂/100 km", 2, 25, "Consumo específico em ciclo urbano.", 2, true),
  "h2.consumoRegionalKg100km": n("Consumo — regional", "kg H₂/100 km", 2, 25, "Consumo específico em ciclo regional.", 2, true),
  "h2.consumoRodoviarioKg100km": n("Consumo — rodoviário", "kg H₂/100 km", 2, 25, "Consumo específico em rodovia. Faixa de referência para cavalo mecânico: 7,5 a 9,0 kg/100 km.", 2, true),
  "h2.cargaReferenciaT": n("Carga de referência do consumo", "t", 0, 50, "Carga à qual os consumos declarados se referem."),
  "h2.ajusteConsumoPorTonKg100km": n("Ajuste por tonelada", "kg/100 km por t", 0, 2, "Acréscimo de consumo por tonelada acima da carga de referência.", 3),
  "h2.degradacaoPilhaPct1000h": p("Degradação da pilha", 0, 5, "Queda de eficiência a cada 1.000 horas de operação, convertida em aumento proporcional de consumo ao longo do horizonte.", 2, true),
  "h2.perdasAbastecimentoPct": p("Perdas de abastecimento e purga", 0, 15, "Percentual do hidrogênio perdido em transferência e purga."),
  "h2.tempoAbastecimentoMin": n("Tempo de abastecimento", "min/evento", 3, 90, "Tempo por evento de abastecimento.", 0),
  "h2.eficienciaPilha": n("Eficiência da pilha", "fração", 0.3, 0.7, "Eficiência do sistema de célula a combustível. Faixa aceitável 40%–55%.", 3),
  "h2.modoSuprimento": s("Modo de suprimento de H₂", [{ value: "A", label: "A — Comprado e entregue" }, { value: "B", label: "B — Eletrólise própria" }, { value: "C", label: "C — Biomassa / looping químico" }], "Define como o custo do hidrogênio é formado. Os três modos produzem um custo em R$/kg comparável na aba de resultados."),
  "h2.aPrecoKg": n("Preço do H₂ na porta", "R$/kg", 5, 120, "Preço contratado do hidrogênio entregue na base.", 2, true),
  "h2.aPrecoIncluiIcms": b("Preço já inclui ICMS", "Quando desmarcado, o ICMS informado na aba Missão é acrescido ao preço."),
  "h2.aDistanciaFonteKm": n("Distância da fonte", "km", 0, 2000, "Distância entre o produtor e a base da frota.", 0),
  "h2.aCustoLogisticoKg": n("Custo logístico adicional", "R$/kg", 0, 60, "Transporte em tube trailer, além do preço na porta da planta.", 2, true),
  "h2.aPerdasTransferenciaPct": p("Perdas de transferência", 0, 20, "Hidrogênio perdido na descarga do tube trailer."),
  "h2.aTakeOrPayKgAno": n("Volume mínimo (take-or-pay)", "kg/ano", 0, 500000, "Volume contratual mínimo. Se o consumo ficar abaixo, a diferença é penalizada.", 0),
  "h2.aPenalidadeKg": n("Penalidade de take-or-pay", "R$/kg", 0, 120, "Valor pago por quilo não retirado dentro do volume mínimo.", 2),
  "h2.bCapexEletrolisadorRSKW": n("CAPEX do eletrolisador", "R$/kW", 1000, 20000, "CAPEX instalado por kW, incluindo balanço de planta.", 0, true),
  "h2.bPotenciaKW": n("Potência do eletrolisador", "kW", 50, 50000, "Potência nominal instalada.", 0),
  "h2.bConsumoKWhKg": n("Consumo específico da eletrólise", "kWh/kg H₂", 40, 80, "Consumo do sistema completo. Faixa de referência 52 a 55 kWh/kg.", 1, true),
  "h2.bDegradacaoStackPctAno": p("Degradação do stack", 0, 10, "Perda anual de eficiência do stack, convertida em aumento de consumo específico.", 2),
  "h2.bCustoStackRSKW": n("Custo de reposição do stack", "R$/kW", 0, 10000, "Custo da troca do stack ao fim da vida em horas.", 0),
  "h2.bVidaStackHoras": n("Vida do stack", "h", 10000, 150000, "Horas de operação até a reposição.", 0),
  "h2.bAguaLKg": n("Consumo de água desmineralizada", "L/kg H₂", 8, 30, "Água consumida por quilo de hidrogênio, incluindo perdas do tratamento.", 1),
  "h2.bCustoAguaRSm3": n("Custo da água tratada", "R$/m³", 0, 200, "Custo de captação e desmineralização.", 2),
  "h2.bCompressaoKWhKg": n("Compressão", "kWh/kg", 0, 15, "Energia de compressão até a pressão de estocagem.", 2),
  "h2.bCapexArmazenamentoRSKg": n("CAPEX de armazenamento", "R$/kg estocado", 0, 20000, "Investimento por quilo de capacidade de estoque.", 0),
  "h2.bEstoqueKg": n("Estoque dimensionado", "kg", 0, 20000, "Capacidade de estocagem da planta.", 0),
  "h2.bPreResfriamentoKWhKg": n("Pré-resfriamento", "kWh/kg", 0, 5, "Energia de resfriamento a -40 °C exigida no abastecimento rápido.", 2),
  "h2.bFatorCapacidadePct": p("Fator de capacidade da planta", 10, 100, "Percentual do tempo em que a planta opera na potência nominal. Impacta diretamente o rateio do CAPEX por quilo.", 1, true),
  "h2.bOpexFixoPctCapexAno": p("OPEX fixo da planta", 0, 20, "Operação, manutenção e seguros, em % do CAPEX ao ano.", 1),
  "h2.bPrecoEnergiaRSKWh": n("Preço da energia dedicada", "R$/kWh", 0.05, 2, "Custo da energia usada na eletrólise: rede, PPA renovável ou geração própria.", 3, true),
  "h2.bVidaPlantaAnos": n("Vida da planta", "anos", 5, 40, "Prazo de amortização do CAPEX da planta de eletrólise.", 0),
  "h2.cCustoBiomassaRSt": n("Custo da biomassa", "R$/t base úmida", 0, 1000, "Preço posto na planta.", 0, true),
  "h2.cUmidadePct": p("Umidade da biomassa", 0, 70, "Teor de umidade, usado para converter para base seca.", 1),
  "h2.cRendimentoKgPorT": n("Rendimento", "kg H₂/t seca", 10, 150, "Produção de hidrogênio por tonelada de biomassa seca.", 1, true),
  "h2.cCapexPlanta": m("CAPEX da planta", 0, 1000000000, "Investimento total da planta de biomassa ou looping químico."),
  "h2.cCapacidadeKgDia": n("Capacidade da planta", "kg H₂/dia", 10, 100000, "Produção nominal diária.", 0),
  "h2.cOpexFixoPctAno": p("OPEX fixo", 0, 20, "Percentual do CAPEX ao ano."),
  "h2.cOpexVariavelRSKg": n("OPEX variável", "R$/kg", 0, 30, "Custos variáveis além da biomassa.", 2),
  "h2.cCoprodutoTPorTBiomassa": n("Coproduto gerado", "t/t biomassa", 0, 2, "Biocarbono, CO₂ biogênico ou calor por tonelada processada.", 3),
  "h2.cCreditoCoprodutoRSt": n("Crédito por coproduto", "R$/t", 0, 5000, "Receita obtida com a venda dos coprodutos.", 0),
  "h2.cVidaPlantaAnos": n("Vida da planta", "anos", 5, 40, "Prazo de amortização do CAPEX.", 0),
  "h2.usarHrsPropria": b("Estação de abastecimento própria", "Quando desmarcado, o CAPEX da estação é substituído pelo custo de abastecimento móvel por quilo."),
  "h2.hrsCapex": m("CAPEX da estação (HRS)", 0, 100000000, "Compressor, armazenamento, dispenser e obra civil."),
  "h2.hrsVidaAnos": n("Vida útil da estação", "anos", 5, 30, "Prazo de amortização da HRS.", 0),
  "h2.hrsOpexPctCapexAno": p("OPEX da estação", 0, 20, "Manutenção anual em % do CAPEX."),
  "h2.hrsConsumoKWhKg": n("Consumo elétrico da estação", "kWh/kg", 0, 10, "Compressão e pré-resfriamento na própria estação.", 2),
  "h2.hrsPrecoEnergiaRSKWh": n("Preço da energia da estação", "R$/kWh", 0.05, 3, "Tarifa aplicada ao consumo da HRS.", 3),
  "h2.hrsCapacidadeKgDia": n("Capacidade da estação", "kg H₂/dia", 50, 20000, "Capacidade nominal de despacho da estação. Junto com a taxa de utilização, define o volume sobre o qual o CAPEX é diluído.", 0, true),
  "h2.hrsUtilizacaoPct": p("Taxa de utilização da estação", 5, 100, "Percentual da capacidade nominal efetivamente despachado. Abaixo de 50% o rateio do CAPEX domina o custo do quilo. O número de veículos equivalentes atendidos é calculado a partir desta taxa.", 1, true),
  "h2.hrsMovelRSKg": n("Abastecimento móvel", "R$/kg", 0, 60, "Custo adicional por quilo no abastecimento itinerante, sem CAPEX fixo.", 2),
  "h2.vidaPilhaHoras": n("Vida da pilha", "h", 5000, 100000, "Horas de operação até a substituição da célula a combustível.", 0, true),
  "h2.custoPilhaRSKW": n("Custo de substituição da pilha", "R$/kW", 0, 10000, "Custo por kW da pilha nova instalada.", 0, true),
  "h2.bateriaTampaoVidaAnos": n("Vida da bateria tampão", "anos", 2, 20, "Prazo até a substituição do pack tampão.", 0),
  "h2.custoBateriaTampaoRSKWh": n("Custo da bateria tampão", "R$/kWh", 0, 5000, "Custo de substituição por kWh.", 0),
  "h2.consumiveisCusto": m("Consumíveis específicos", 0, 50000, "Filtro de ar catalítico, resina deionizadora e sistema de umidificação, por intervenção."),
  "h2.consumiveisIntervaloKm": n("Intervalo dos consumíveis", "km", 10000, 500000, "Quilometragem entre substituições.", 0),
  "h2.inspecaoCilindrosAnos": n("Inspeção de cilindros — intervalo", "anos", 1, 15, "Periodicidade da inspeção obrigatória dos cilindros de alta pressão.", 0),
  "h2.inspecaoCilindrosCusto": m("Inspeção de cilindros — custo", 0, 200000, "Custo por inspeção, incluindo imobilização para ensaio."),
  "h2.vidaNormativaCilindrosAnos": n("Vida normativa dos cilindros", "anos", 5, 30, "Prazo após o qual os cilindros precisam ser substituídos por norma.", 0),
  "h2.preventivaPorKm": n("Manutenção preventiva", "R$/km", 0, 3, "Custo programado por quilômetro, exceto itens detalhados.", 3),
  "h2.corretivaAno1": m("Corretiva no primeiro ano", 0, 300000, "Manutenção não programada no ano 1."),
  "h2.corretivaCrescimentoPctAA": p("Crescimento da corretiva", 0, 60, "Crescimento anual composto da corretiva.", 1),
  "h2.fatorVidaPneu": n("Fator de vida do pneu", "x", 0.5, 1.5, "Vida do pneu em relação ao diesel. Menor por conta da massa adicional.", 3),
  "h2.fatorVidaFreio": n("Fator de vida do freio", "x", 0.5, 4, "Vida do freio ampliada pela frenagem regenerativa.", 3),
  "h2.horasParadoManutAno": n("Horas paradas em manutenção", "h/ano", 0, 2000, "Tempo anual indisponível por manutenção programada.", 0),
  "h2.falhaProbAno": n("Panes não programadas", "eventos/ano", 0, 10, "Frequência de falhas imobilizantes.", 2),
  "h2.falhaHorasEvento": n("Duração da pane", "h/evento", 0, 300, "Tempo médio de imobilização, incluindo disponibilidade de peças.", 0),
  "h2.adequacaoGaragemCapex": m("Adequação da garagem", 0, 10000000, "Detecção de vazamento, ventilação e classificação de área para veículos a hidrogênio."),
  "h2.adequacaoGaragemOpexAno": m("OPEX da adequação de garagem", 0, 1000000, "Manutenção anual dos sistemas de segurança."),
  "h2.treinamentoRecorrenteAno": m("Treinamento recorrente", 0, 200000, "Reciclagem anual da equipe para manuseio de hidrogênio."),
  "h2.zonaRestritaPctRotas": p("Rotas afetadas por restrição", 0, 100, "Percentual de rotas com restrição de acesso — normalmente zero para emissão zero."),
  "h2.choqueResidualPct": p("Choque no valor residual", 0, 100, "Desvalorização adicional no ano final, por incerteza de mercado secundário."),
  "h2.residual": t("Curva de valor residual", "Percentual do preço de aquisição retido a cada ano, editável ponto a ponto."),
});

// ── ELÉTRICO ──────────────────────────────────────────────────────────────
Object.assign(FIELDS, {
  "bev.modoPreco": s("Origem do preço do veículo", [{ value: "direto", label: "Preço direto em R$" }, { value: "importacao", label: "Calcular pela importação" }], "No modo importação o preço é montado a partir do FOB em dólar, frete, seguro, II, IPI, ICMS e despacho."),
  "bev.precoAquisicao": m("Preço de aquisição", 0, 20000000, "Preço do BEV pesado entregue. Estimativa 2026.", true),
  "bev.precoSemImpostos": m("Preço sem impostos", 0, 20000000, "Valor líquido, base de créditos quando aplicável."),
  "bev.impFobUsd": n("FOB", "US$", 0, 3000000, "Valor FOB do veículo na origem.", 0),
  "bev.impFreteSeguroPct": p("Frete e seguro internacional", 0, 40, "Percentual sobre o FOB para chegar ao CIF.", 1),
  "bev.impIiPct": p("Imposto de Importação", 0, 60, "Alíquota do II. Zero quando há ex-tarifário."),
  "bev.impIpiPct": p("IPI", 0, 40, "Alíquota de IPI na importação."),
  "bev.impIcmsPct": p("ICMS na importação", 0, 40, "Alíquota de ICMS do estado de desembaraço."),
  "bev.impDespachoPct": p("Despacho e armazenagem", 0, 20, "Custos de desembaraço e transporte interno, em % do CIF."),
  "bev.capacidadeKWh": n("Capacidade nominal da bateria", "kWh", 100, 1500, "Energia nominal do pack.", 0, true),
  "bev.socMinPct": p("SOC mínimo", 0, 50, "Limite inferior da janela de uso. Default 10%.", 0),
  "bev.socMaxPct": p("SOC máximo", 50, 100, "Limite superior da janela de uso. Default 90%.", 0),
  "bev.massaPackKgPorKWh": n("Massa específica do pack", "kg/kWh", 3, 12, "Massa do pack por kWh nominal. Default 5,5 kg/kWh para pack de veículo pesado.", 2, true),
  "bev.massaExtraSistemaKg": n("Massa dos demais componentes", "kg", 0, 3000, "Motores, inversor, DC-DC e refrigeração do pack.", 0),
  "bev.potenciaRecargaCcKW": n("Potência máxima de recarga CC", "kW", 20, 1500, "Potência que o veículo aceita em corrente contínua.", 0),
  "bev.potenciaRecargaCaKW": n("Potência máxima de recarga CA", "kW", 0, 100, "Potência aceita em corrente alternada.", 0),
  "bev.quimica": s("Química da bateria", [{ value: "LFP", label: "LFP" }, { value: "NMC", label: "NMC" }, { value: "semiSolida", label: "Semi-sólida" }], "A química define os defaults de ciclos, degradação e custo. Trocar a química não sobrescreve valores já editados: ajuste os campos do bloco de vida útil conforme a tecnologia."),
  "bev.taraBaseT": n("Tara base (sem sistema de energia)", "t", 5, 30, "Massa do conjunto sem pack, motores e refrigeração.", 2),
  "bev.pbtcT": n("PBTC legal", "t", 10, 100, "Peso bruto total combinado permitido.", 1),
  "bev.toleranciaRegulatoriaT": n("Tolerância regulatória de peso", "t", 0, 3, "Tolerância adicional de PBTC concedida a veículos de emissão zero. Default zero.", 2, true),
  "bev.vidaUtilAnos": n("Vida útil operacional", "anos", 1, 25, "Vida econômica considerada.", 0),
  "bev.consumoUrbanoKWhKm": n("Consumo — urbano", "kWh/km", 0.4, 3, "Consumo específico em ciclo urbano, medido no pack.", 3, true),
  "bev.consumoRegionalKWhKm": n("Consumo — regional", "kWh/km", 0.4, 3, "Consumo específico em ciclo regional.", 3, true),
  "bev.consumoRodoviarioKWhKm": n("Consumo — rodoviário", "kWh/km", 0.4, 3, "Consumo em rodovia. Faixa de referência para cavalo mecânico: 1,1 a 1,5 kWh/km.", 3, true),
  "bev.cargaReferenciaT": n("Carga de referência do consumo", "t", 0, 50, "Carga à qual os consumos declarados se referem."),
  "bev.ajusteConsumoPorTonKWhKm": n("Ajuste por tonelada", "kWh/km por t", 0, 0.2, "Acréscimo de consumo por tonelada acima da carga de referência.", 4),
  "bev.regenUrbanoPct": p("Ganho regenerativo — urbano", 0, 40, "Recuperação de energia em frenagem no ciclo urbano, já descontada do consumo declarado se este for líquido. Aqui é aplicada como redução adicional.", 1),
  "bev.regenRegionalPct": p("Ganho regenerativo — regional", 0, 40, "Recuperação de energia em ciclo regional.", 1),
  "bev.regenRodoviarioPct": p("Ganho regenerativo — rodoviário", 0, 40, "Recuperação em rodovia, tipicamente baixa.", 1),
  "bev.climatizacaoBaseKWhDia": n("Climatização — base", "kWh/dia", 0, 100, "Consumo diário de climatização de cabine na temperatura neutra.", 1),
  "bev.climatizacaoPorGrauKWhDia": n("Climatização — sensibilidade térmica", "kWh/dia por °C", 0, 5, "Consumo adicional por grau de desvio em relação a 20 °C, cobrindo cabine e condicionamento do pack.", 2),
  "bev.eficienciaCarregamentoPct": p("Eficiência de carregamento", 60, 100, "Perdas do carregador somadas às do sistema de bordo. Default 90%.", 1),
  "bev.autodescargaPctDia": p("Autodescarga e standby", 0, 3, "Perda diária de energia com o veículo parado.", 3),
  "bev.degradacaoCalendariaPctAno": p("Degradação calendárica", 0, 10, "Perda anual de capacidade independente do uso. Default 2% a.a.", 2, true),
  "bev.ciclosAte80Soh": n("Ciclos até 80% de SOH", "ciclos", 500, 8000, "Ciclos equivalentes completos até a capacidade cair a 80%. Referência: LFP 3.000–4.000, NMC 2.500, semi-sólida acima de 4.000.", 0, true),
  "bev.dodMedioPct": p("Profundidade de descarga média", 10, 100, "DOD médio por ciclo, usado para converter energia consumida em ciclos equivalentes.", 1),
  "bev.pctRecargaAltaPotencia": p("Recargas acima de 1C", 0, 100, "Percentual da energia reposta em alta potência.", 1),
  "bev.fatorAltaPotencia": n("Agravante de alta potência", "x", 1, 2, "Multiplicador da taxa de degradação aplicado à parcela recarregada em alta potência.", 3),
  "bev.fatorTemperaturaPorGrau": n("Agravante térmico", "x/°C", 0, 0.1, "Acréscimo do multiplicador de degradação por grau acima de 25 °C.", 3),
  "bev.fatorSocAlto": n("Agravante de SOC alto", "x", 1, 2, "Multiplicador por permanência prolongada em estado de carga elevado.", 3),
  "bev.sohMinimoPct": p("SOH mínimo aceitável", 50, 95, "Critério de substituição do pack. Default 80%. O modelo também testa se a autonomia degradada atende ao trecho mais longo e adota o critério que ocorrer primeiro.", 1, true),
  "bev.custoPackRSKWh": n("Custo do pack de reposição", "R$/kWh", 100, 3000, "Custo hoje do pack novo instalado. Projetado no tempo pela curva de aprendizado.", 0, true),
  "bev.curvaAprendizadoPackPctAA": p("Curva de aprendizado do pack", -20, 5, "Variação real do custo do pack por ano. Default -6% a.a.", 2, true),
  "bev.garantiaAnos": n("Garantia do pack — prazo", "anos", 0, 15, "Prazo de garantia do fabricante.", 0),
  "bev.garantiaKm": n("Garantia do pack — quilometragem", "km", 0, 2000000, "Limite de quilometragem da garantia.", 0),
  "bev.garantiaSohPct": p("SOH garantido", 0, 100, "Capacidade mínima garantida dentro do prazo. Se a substituição ocorrer dentro da garantia e abaixo deste SOH, o custo é abatido.", 1),
  "bev.valorSecondLifeRSKWh": n("Valor do pack removido", "R$/kWh", 0, 1000, "Receita de segunda vida do pack retirado.", 0),
  "bev.custoReciclagemRSKWh": n("Custo de reciclagem", "R$/kWh", 0, 500, "Custo de destinação, quando não há valor de segunda vida.", 0),
  "bev.numCarregadores": n("Número de carregadores", "un", 1, 100, "Carregadores instalados na base.", 0),
  "bev.potenciaCarregadorKW": n("Potência por carregador", "kW", 20, 1000, "Potência nominal de cada carregador.", 0, true),
  "bev.capexPorCarregador": m("CAPEX por carregador", 0, 3000000, "Equipamento instalado, por unidade."),
  "bev.obraCivil": m("Obra civil e cabeamento", 0, 10000000, "Infraestrutura civil, cabeamento e proteção."),
  "bev.subestacao": m("Entrada de energia e subestação", 0, 20000000, "Transformador, cabine primária e entrada."),
  "bev.conexaoReforcoRede": m("Conexão e reforço de rede", 0, 30000000, "Custo cobrado pela distribuidora para viabilizar a demanda adicional."),
  "bev.infraVidaAnos": n("Vida da infraestrutura", "anos", 3, 30, "Prazo de amortização dos carregadores e da obra.", 0),
  "bev.infraOemPctAno": p("O&M da infraestrutura", 0, 20, "Manutenção anual em % do CAPEX."),
  "bev.infraSoftwareMes": m("Software e rede", 0, 20000, "Mensalidade de gestão de recarga por ponto."),
  "bev.infraVeiculosRateio": n("Veículos no rateio da infraestrutura", "un", 1, 200, "Número de veículos entre os quais o CAPEX de recarga é rateado.", 0, true),
  "bev.modalidade": s("Modalidade tarifária", [{ value: "cativoVerde", label: "Cativo — Grupo A Verde" }, { value: "cativoAzul", label: "Cativo — Grupo A Azul" }, { value: "livre", label: "Mercado livre (ACL)" }, { value: "autoproducao", label: "Autoprodução" }], "Na tarifa Verde a demanda é única; na Azul há demanda de ponta e fora de ponta. No mercado livre a TE é contratada e a TUSD permanece regulada."),
  "bev.teForaPontaRSMWh": n("TE fora de ponta", "R$/MWh", 0, 3000, "Tarifa de energia fora do horário de ponta.", 2, true),
  "bev.tePontaRSMWh": n("TE ponta", "R$/MWh", 0, 5000, "Tarifa de energia no horário de ponta.", 2),
  "bev.tusdForaPontaRSMWh": n("TUSD fora de ponta", "R$/MWh", 0, 3000, "Uso do sistema de distribuição fora de ponta.", 2),
  "bev.tusdPontaRSMWh": n("TUSD ponta", "R$/MWh", 0, 5000, "Uso do sistema no horário de ponta — na tarifa Verde é o componente que torna a recarga em ponta proibitiva.", 2),
  "bev.demandaContratadaKW": n("Demanda contratada", "kW", 0, 20000, "Demanda contratada junto à distribuidora. O modelo compara com o pico gerado pela recarga simultânea.", 0, true),
  "bev.tarifaDemandaRSKWMes": n("Tarifa de demanda", "R$/kW·mês", 0, 200, "Valor pago por kW contratado por mês.", 2, true),
  "bev.multaUltrapassagemFator": n("Fator de multa por ultrapassagem", "x", 1, 4, "Multiplicador aplicado à parcela de demanda que exceder a contratada.", 2),
  "bev.fatorSimultaneidade": n("Fator de simultaneidade", "fração", 0.1, 1, "Fração dos carregadores operando ao mesmo tempo no pico.", 2, true),
  "bev.bandeiraRSMWh": n("Bandeiras tarifárias", "R$/MWh médio", 0, 500, "Custo médio anualizado das bandeiras.", 2),
  "bev.icmsEnergiaPct": p("ICMS sobre energia", 0, 40, "Alíquota estadual aplicada à conta de energia da base."),
  "bev.pctPonta": p("Recarga em ponta", 0, 100, "Percentual da energia reposta no horário de ponta. Os três percentuais somam 100%.", 1),
  "bev.pctForaPonta": p("Recarga fora de ponta", 0, 100, "Percentual reposto fora de ponta, no período diurno.", 1),
  "bev.pctMadrugada": p("Recarga na madrugada", 0, 100, "Percentual reposto na madrugada.", 1),
  "bev.descontoMadrugadaPct": p("Desconto tarifário na madrugada", 0, 80, "Desconto eventual sobre a TE no período noturno.", 1),
  "bev.solarUsar": b("Geração solar própria", "Quando ativo, parte da energia é suprida por geração própria, ao custo amortizado do investimento (Lei 14.300/2022)."),
  "bev.solarCapexRSkWp": n("CAPEX solar", "R$/kWp", 1000, 12000, "Investimento por kWp instalado.", 0),
  "bev.solarKWp": n("Potência solar instalada", "kWp", 0, 20000, "Potência da usina própria.", 0),
  "bev.solarFatorCapacidadePct": p("Fator de capacidade solar", 5, 40, "Percentual médio de geração sobre a potência instalada.", 1),
  "bev.solarVidaAnos": n("Vida da usina solar", "anos", 5, 35, "Prazo de amortização da geração própria.", 0),
  "bev.armazenamentoKWh": n("Armazenamento estacionário", "kWh", 0, 20000, "Capacidade de baterias estacionárias na base.", 0),
  "bev.armazenamentoRSKWh": n("Custo do armazenamento", "R$/kWh", 0, 6000, "CAPEX por kWh do sistema estacionário.", 0),
  "bev.pctRecargaPublica": p("Recarga fora da base", 0, 100, "Percentual da energia obtida em eletropostos públicos ou de rota.", 1, true),
  "bev.precoRecargaPublicaRSKWh": n("Preço da recarga pública", "R$/kWh", 0.3, 10, "Preço por kWh na recarga de rota.", 2, true),
  "bev.pctRecargaForaJanela": p("Recarga fora da janela operacional", 0, 100, "Percentual da recarga feita quando o veículo já estaria parado — não gera indisponibilidade.", 1, true),
  "bev.taperFator": n("Fator de taper", "fração", 0.3, 1, "Relação entre a potência média efetiva de recarga e a nominal, considerando a redução acima de 80% de SOC.", 2),
  "bev.filaFator": n("Disponibilidade de ponto livre", "fração", 0.3, 1, "Fração do tempo em que há carregador livre ao chegar. Valores baixos aumentam o tempo parado.", 2),
  "bev.preventivaPorKm": n("Manutenção preventiva", "R$/km", 0, 3, "Custo programado por quilômetro. Tipicamente 30% a 50% do diesel.", 3, true),
  "bev.fatorVidaPneu": n("Fator de vida do pneu", "x", 0.4, 1.5, "Vida do pneu em relação ao diesel, reduzida pelo peso e pelo torque instantâneo.", 3),
  "bev.fatorVidaFreio": n("Fator de vida do freio", "x", 0.5, 4, "Vida ampliada pela frenagem regenerativa.", 3),
  "bev.fluidosCusto": m("Fluidos e itens específicos", 0, 50000, "Arrefecimento do pack, inversor, motor elétrico e DC-DC, por intervenção."),
  "bev.fluidosIntervaloKm": n("Intervalo dos fluidos", "km", 10000, 500000, "Quilometragem entre intervenções.", 0),
  "bev.falhaPackProbAnoPct": p("Falha do pack fora da garantia", 0, 20, "Probabilidade anual de falha relevante do pack após o fim da garantia.", 2),
  "bev.falhaPackCusto": m("Custo do evento de falha do pack", 0, 3000000, "Reparo ou substituição parcial de módulos."),
  "bev.corretivaAno1": m("Corretiva no primeiro ano", 0, 300000, "Manutenção não programada no ano 1."),
  "bev.corretivaCrescimentoPctAA": p("Crescimento da corretiva", 0, 60, "Crescimento anual composto da corretiva.", 1),
  "bev.horasParadoManutAno": n("Horas paradas em manutenção", "h/ano", 0, 2000, "Tempo anual indisponível por manutenção programada.", 0),
  "bev.falhaProbAno": n("Panes não programadas", "eventos/ano", 0, 10, "Frequência de falhas imobilizantes.", 2),
  "bev.falhaHorasEvento": n("Duração da pane", "h/evento", 0, 300, "Tempo médio de imobilização.", 0),
  "bev.zonaRestritaPctRotas": p("Rotas afetadas por restrição", 0, 100, "Percentual de rotas com restrição de acesso."),
  "bev.choqueResidualPct": p("Choque no valor residual", 0, 100, "Desvalorização adicional no ano final."),
  "bev.residual": t("Curva de valor residual", "Percentual do preço de aquisição retido a cada ano, editável ponto a ponto."),
  "diesel.residual": t("Curva de valor residual", "Percentual do preço de aquisição retido a cada ano, editável ponto a ponto. Referência: tabela FIPE de pesados."),
});



// ── GÁS NATURAL E BIOMETANO ───────────────────────────────────────────────
Object.assign(FIELDS, {
  "fin.jurosGas": p("Juros — Gás", 0, 40, "Taxa anual da linha usada para o caminhão a gás. O gás não se enquadra nas linhas de emissão zero, então a referência costuma ser o Finame convencional.", 2, true),
  "fin.aluguelMensalGas": m("Aluguel mensal — Gás", 0, 300000, "Mensalidade no regime de aluguel/locação, quando aplicável."),
  "trib.icmsGasPct": p("ICMS sobre o gás", 0, 40, "Alíquota estadual sobre gás natural veicular e biometano. Vários estados concedem redução de base para o biometano."),
  "trib.depAnosGas": n("Depreciação fiscal — Gás", "anos", 1, 25, "Prazo de depreciação fiscal do veículo a gás e da estação de abastecimento.", 0),
  "trib.ipvaPctGas": p("IPVA — Gás", 0, 6, "Percentual do valor venal."),
  "trib.incentivoCapexPctGas": p("Incentivo sobre CAPEX — Gás", 0, 60, "Crédito ou subvenção como percentual do CAPEX (programas estaduais de gás e de biometano)."),
  "trib.incentivoAnualGas": m("Incentivo anual — Gás", 0, 2000000, "Crédito fiscal recorrente, em R$/ano por veículo."),
  "comuns.treinamentoGas": m("Treinamento — Gás", 0, 50000, "Custo único por motorista para operação e abastecimento com gás pressurizado."),
  "comuns.seguroPctGas": p("Seguro — Gás", 0, 15, "Prêmio anual como percentual do valor do ativo.", 2, true),

  "carbono.gwpMetano": n("GWP do metano", "x CO₂ em 100 anos", 1, 100, "Potencial de aquecimento global do metano em horizonte de 100 anos. AR5 do IPCC usa 28; o AR6 traz 27,9 para metano não fóssil e 29,8 para fóssil. É este número que transforma o metano não queimado em CO₂ equivalente.", 1, true),
  "carbono.fatorGnvCombustaoKgKg": n("Emissão de combustão — gás natural", "kgCO₂e/kg", 0, 5, "Queima completa do metano: 16,04 g de CH₄ produzem 44,01 g de CO₂, ou 2,74 kg por quilo. Aplicado apenas à parcela efetivamente queimada.", 3),
  "carbono.fatorGnvUpstreamKgKg": n("Upstream — gás natural", "kgCO₂e/kg", 0, 5, "Produção, processamento, transporte e distribuição do gás natural até o ponto de abastecimento.", 3, true),
  "carbono.fatorBioCombustaoKgKg": n("Emissão de combustão — biometano", "kgCO₂e/kg", 0, 5, "O CO₂ da queima do biometano é de origem biogênica e por convenção não entra no inventário. Mantenha zero salvo se a metodologia adotada exigir contabilizá-lo.", 3),
  "carbono.fatorBioUpstreamKgKg": n("Upstream — biometano", "kgCO₂e/kg", 0, 5, "Digestão anaeróbia, purificação, compressão e transporte. Estimativa de engenharia.", 3, true),
  "carbono.fatorBioEvitadoKgKg": n("Crédito de emissão evitada — biometano", "kgCO₂e/kg", -30, 5, "Metano que deixaria de escapar de lagoa de dejetos, aterro ou vinhaça se o substrato não fosse digerido. Informe valor NEGATIVO para creditar. Em dejetos suínos e bovinos esse crédito costuma superar toda a emissão da cadeia, tornando a pegada líquida negativa.", 3, true),
  "carbono.noxGnvGkm": n("NOx — Gás", "g/km", 0, 10, "Motor a gás estequiométrico com catalisador de três vias emite bem menos NOx que um ciclo Diesel com SCR.", 3),
  "carbono.mpGnvGkm": n("Material particulado — Gás", "g/km", 0, 1, "A combustão do metano praticamente não gera particulado de escapamento.", 4),

  "gas.modoPreco": s("Origem do preço do veículo", [{ value: "direto", label: "Preço direto em R$" }, { value: "importacao", label: "Calcular pela importação" }], "No modo importação o preço é montado a partir do FOB em dólar, frete, seguro, II, IPI, ICMS e despacho."),
  "gas.precoAquisicao": m("Preço de aquisição", 0, 10000000, "Preço do cavalo mecânico a gás. Costuma ficar 20% a 30% acima do diesel equivalente. Estimativa 2026.", true),
  "gas.precoSemImpostos": m("Preço sem impostos", 0, 10000000, "Valor líquido de ICMS/IPI, base para créditos quando aplicável."),
  "gas.impFobUsd": n("FOB", "US$", 0, 3000000, "Valor FOB do veículo na origem.", 0),
  "gas.impFreteSeguroPct": p("Frete e seguro internacional", 0, 40, "Percentual sobre o FOB para chegar ao CIF.", 1),
  "gas.impIiPct": p("Imposto de Importação", 0, 60, "Alíquota do II. Zero quando há ex-tarifário."),
  "gas.impIpiPct": p("IPI", 0, 40, "Alíquota de IPI na importação."),
  "gas.impIcmsPct": p("ICMS na importação", 0, 40, "Alíquota de ICMS do estado de desembaraço."),
  "gas.impDespachoPct": p("Despacho e armazenagem", 0, 20, "Custos de desembaraço e transporte interno, em % do CIF."),
  "gas.configuracao": s("Configuração", [{ value: "4x2", label: "4x2" }, { value: "6x2", label: "6x2" }, { value: "6x4", label: "6x4" }], "Configuração de tração do cavalo mecânico."),
  "gas.pbtcT": n("PBTC legal", "t", 10, 100, "Peso bruto total combinado permitido para a configuração.", 1),
  "gas.taraBaseT": n("Tara base (sem sistema de energia)", "t", 5, 30, "Massa do conjunto sem cilindros, gás embarcado e periféricos. Deve ser comparável à tara base declarada nas outras rotas.", 2),
  "gas.potenciaCv": n("Potência", "cv", 100, 800, "Potência nominal do motor a gás. Motores Otto costumam entregar menos potência que o Diesel de mesmo deslocamento.", 0),
  "gas.ciclo": s("Ciclo do motor", [{ value: "otto", label: "Otto estequiométrico (100% gás)" }, { value: "hpdi", label: "HPDI / dual-fuel (com piloto de diesel)" }], "No ciclo Otto o motor roda só com gás e usa catalisador de três vias. No HPDI uma fração da energia vem de um piloto de diesel, o que recupera eficiência mas traz de volta o consumo de ARLA e o pós-tratamento SCR."),
  "gas.pilotoDieselPct": p("Piloto de diesel", 0, 50, "Percentual da energia total fornecido pelo diesel piloto no ciclo HPDI. Faixa típica de 5% a 10%. Sem efeito no ciclo Otto.", 1, true),
  "gas.armazenamento": s("Forma de armazenamento", [{ value: "GNC", label: "GNC — comprimido a 200/250 bar" }, { value: "GNL", label: "GNL — liquefeito a -162 °C" }], "Campo declaratório: registre a forma adotada e ajuste coerentemente a capacidade embarcada, a massa específica do sistema e a evaporação diária. O GNL embarca muito mais energia por quilo de sistema, mas evapora quando o veículo fica parado."),
  "gas.capacidadeKg": n("Capacidade embarcada", "kg", 10, 1200, "Massa de gás armazenada a bordo. GNC em cavalo mecânico fica entre 100 e 200 kg; GNL passa facilmente de 300 kg.", 0, true),
  "gas.massaSistemaKgPorKg": n("Massa do sistema por kg armazenado", "kg/kg", 1, 10, "Massa TOTAL do sistema de armazenamento por quilo de gás, já incluindo o próprio gás. Cilindros tipo III/IV a 200 bar ficam perto de 4 kg/kg; um sistema GNL fica em torno de 2,6 kg/kg.", 2, true),
  "gas.massaExtraSistemaKg": n("Massa dos demais componentes", "kg", 0, 1500, "Redutor de pressão, linhas de alta, chicote e catalisador de três vias.", 0),
  "gas.pciKWhKg": n("Poder calorífico do gás natural", "kWh/kg", 10, 16, "PCI do gás natural distribuído. Varia com a composição: 13,0 a 13,5 kWh/kg é a faixa usual no Brasil. Metano puro chega a 13,9.", 2),
  "gas.densidadeKgM3": n("Densidade do gás natural", "kg/m³", 0.5, 1.2, "Densidade nas condições em que o metro cúbico é faturado (20 °C e 1 atm). É o número que converte R$/m³ em R$/kg.", 3),
  "gas.vidaUtilAnos": n("Vida útil operacional", "anos", 1, 25, "Vida econômica considerada para o ativo.", 0),
  "gas.residual": t("Curva de valor residual", "Percentual do preço de aquisição retido a cada ano, editável ponto a ponto. O mercado secundário de caminhões a gás ainda é estreito no Brasil, o que puxa a curva para baixo."),
  "gas.consumoUrbanoKg100km": n("Consumo — urbano", "kg/100 km", 5, 80, "Consumo específico em ciclo urbano, na carga de referência.", 2, true),
  "gas.consumoRegionalKg100km": n("Consumo — regional", "kg/100 km", 5, 80, "Consumo específico em ciclo regional.", 2, true),
  "gas.consumoRodoviarioKg100km": n("Consumo — rodoviário", "kg/100 km", 5, 80, "Consumo em rodovia. Um cavalo mecânico a gás carregado consome de 25 a 32 kg/100 km. Declare sempre na base do gás natural: o motor corrige sozinho para o poder calorífico do biometano.", 2, true),
  "gas.cargaReferenciaT": n("Carga de referência do consumo", "t", 0, 50, "Carga transportada à qual os consumos declarados se referem."),
  "gas.ajusteConsumoPorTonKg100km": n("Ajuste por tonelada", "kg/100 km por t", 0, 5, "Acréscimo de consumo por tonelada acima da carga de referência.", 3),
  "gas.slipMetanoPct": p("Metano não queimado (slip)", 0, 10, "Percentual do gás que atravessa o motor sem queimar. É o parâmetro mais sensível de toda a rota a gás: com GWP de 28, um slip de 1% já consome boa parte da vantagem climática do gás fóssil sobre o diesel. Motor estequiométrico com catalisador fica abaixo de 1%; lean-burn pode passar de 3%.", 2, true),
  "gas.pctMarchaLenta": p("Tempo em marcha lenta", 0, 60, "Percentual das horas de operação com o motor em marcha lenta.", 1),
  "gas.consumoMarchaLentaKgH": n("Consumo em marcha lenta", "kg/h", 0, 10, "Consumo horário com o veículo parado e motor ligado.", 2),
  "gas.perdasBoilOffPctDia": p("Evaporação diária (boil-off)", 0, 5, "Percentual do gás liquefeito que evapora por dia com o veículo parado. Zero para GNC; entre 0,2% e 0,5% ao dia para GNL. É a razão pela qual o GNL não combina com operação intermitente.", 3, true),
  "gas.tempoAbastecimentoMin": n("Tempo de abastecimento", "min/evento", 3, 90, "Tempo por evento de abastecimento, incluindo deslocamento e fila.", 0),
  "gas.eficienciaMotor": n("Eficiência do motor", "fração", 0.15, 0.5, "Eficiência térmica média do motor a gás, usada no PTO e no balanço energético. Fica abaixo do ciclo Diesel equivalente.", 3),
  "gas.preventivaPorKm": n("Manutenção preventiva", "R$/km", 0, 3, "Custo programado por quilômetro, excluindo velas, catalisador e filtros, detalhados à parte.", 3, true),
  "gas.velasCusto": m("Velas e ignição — custo", 0, 30000, "Jogo completo de velas e bobinas por intervenção. É um item que o ciclo Diesel não tem."),
  "gas.velasIntervaloKm": n("Velas e ignição — intervalo", "km", 10000, 300000, "Quilometragem entre substituições.", 0),
  "gas.catalisadorCusto": m("Catalisador de três vias — custo", 0, 100000, "Substituição do catalisador. Faz o papel que o SCR e o DPF fazem no Diesel, com custo menor."),
  "gas.catalisadorVidaKm": n("Catalisador de três vias — vida", "km", 100000, 2000000, "Quilometragem até a substituição.", 0),
  "gas.oleoVolumeL": n("Óleo de motor — volume", "L", 0, 100, "Volume por troca."),
  "gas.oleoPrecoL": n("Óleo de motor — preço", "R$/L", 0, 200, "Motor a gás exige óleo de baixa cinza, mais caro que o lubrificante de motor Diesel."),
  "gas.oleoIntervaloKm": n("Óleo de motor — intervalo", "km", 5000, 200000, "Intervalo entre trocas. Costuma ser menor que no Diesel.", 0),
  "gas.outrosFluidosPctOleo": p("Outros lubrificantes", 0, 200, "Câmbio, diferencial e graxas, como percentual do custo do óleo de motor.", 0),
  "gas.filtrosCusto": m("Filtros — custo", 0, 10000, "Ar, gás e demais filtros, por troca."),
  "gas.filtrosIntervaloKm": n("Filtros — intervalo", "km", 5000, 200000, "Intervalo entre substituições.", 0),
  "gas.inspecaoCilindrosAnos": n("Inspeção de cilindros — intervalo", "anos", 1, 15, "Periodicidade do reteste obrigatório dos cilindros de alta pressão.", 0),
  "gas.inspecaoCilindrosCusto": m("Inspeção de cilindros — custo", 0, 100000, "Custo por inspeção, incluindo a imobilização para ensaio."),
  "gas.vidaNormativaCilindrosAnos": n("Vida normativa dos cilindros", "anos", 5, 30, "Prazo após o qual os cilindros precisam ser substituídos por norma.", 0),
  "gas.altoValorCusto": m("Itens de alto valor — custo", 0, 300000, "Embreagem e sistema de arrefecimento."),
  "gas.altoValorVidaKm": n("Itens de alto valor — vida", "km", 100000, 3000000, "Quilometragem até a intervenção.", 0),
  "gas.corretivaAno1": m("Corretiva no primeiro ano", 0, 200000, "Manutenção não programada no ano 1; cresce com a idade pela taxa abaixo."),
  "gas.corretivaCrescimentoPctAA": p("Crescimento da corretiva", 0, 60, "Crescimento anual composto do custo de manutenção corretiva.", 1),
  "gas.fatorVidaPneu": n("Fator de vida do pneu", "x", 0.4, 1.5, "Vida do pneu em relação ao diesel.", 3),
  "gas.fatorVidaFreio": n("Fator de vida do freio", "x", 0.5, 4, "Vida do freio em relação ao diesel. Sem frenagem regenerativa, fica próximo de 1,00.", 3),
  "gas.horasParadoManutAno": n("Horas paradas em manutenção", "h/ano", 0, 2000, "Tempo anual indisponível por manutenção programada.", 0),
  "gas.falhaProbAno": n("Panes não programadas", "eventos/ano", 0, 10, "Frequência de falhas que imobilizam o veículo.", 2),
  "gas.falhaHorasEvento": n("Duração da pane", "h/evento", 0, 300, "Tempo médio de imobilização por pane.", 0),
  "gas.usarEstacaoPropria": b("Estação de abastecimento própria", "Quando desmarcado, o CAPEX da estação sai do cálculo e presume-se abastecimento em rede pública, cujo custo já deve estar embutido no preço do gás."),
  "gas.estacaoCapex": m("CAPEX da estação", 0, 100000000, "Compressor, estocagem, dispensers e obra civil. Uma estação de GNL exige tanque criogênico e bomba, com custo diferente."),
  "gas.estacaoVidaAnos": n("Vida útil da estação", "anos", 5, 30, "Prazo de amortização da estação.", 0),
  "gas.estacaoOpexPctCapexAno": p("O&M da estação", 0, 20, "Manutenção anual em % do CAPEX."),
  "gas.estacaoConsumoKWhKg": n("Consumo elétrico da estação", "kWh/kg", 0, 5, "Energia de compressão do GNC. No GNL o consumo é bem menor, restrito ao bombeamento.", 3),
  "gas.estacaoPrecoEnergiaRSKWh": n("Preço da energia da estação", "R$/kWh", 0.05, 3, "Tarifa aplicada ao consumo elétrico da estação.", 3),
  "gas.estacaoCapacidadeKgDia": n("Capacidade da estação", "kg/dia", 50, 50000, "Capacidade nominal de despacho. Junto com a taxa de utilização, define o volume sobre o qual o CAPEX é diluído.", 0, true),
  "gas.estacaoUtilizacaoPct": p("Taxa de utilização da estação", 5, 100, "Percentual da capacidade nominal efetivamente despachado. É o que separa uma estação que se paga de uma que afunda a rota a gás.", 1, true),
  "gas.adequacaoGaragemCapex": m("Adequação da garagem", 0, 5000000, "Ventilação, detecção de gás e classificação de área para veículos a gás."),
  "gas.adequacaoGaragemOpexAno": m("O&M da adequação de garagem", 0, 500000, "Manutenção anual dos sistemas de segurança."),
  "gas.treinamentoRecorrenteAno": m("Treinamento recorrente", 0, 200000, "Reciclagem anual da equipe."),
  "gas.zonaRestritaPctRotas": p("Rotas afetadas por restrição", 0, 100, "Percentual de rotas sujeitas a restrição de acesso. O gás reduz muito o NOx e o particulado, mas não é emissão zero."),
  "gas.choqueResidualPct": p("Choque no valor residual", 0, 100, "Desvalorização adicional no ano final, por incerteza do mercado secundário."),

  "gas.gnvMetodoPreco": s("Base de cotação — gás natural", [{ value: "m3", label: "R$ por m³" }, { value: "kg", label: "R$ por kg" }, { value: "mmbtu", label: "R$ por MMBtu" }], "Escolha a base em que o contrato é fechado. A conversão para R$/kg usa a densidade e o poder calorífico declarados acima."),
  "gas.gnvPrecoM3": n("Preço do gás natural", "R$/m³", 0.5, 30, "Preço por metro cúbico. Postos praticam de R$ 4 a R$ 5; contratos de frota com a distribuidora saem abaixo disso.", 3, true),
  "gas.gnvPrecoKg": n("Preço do gás natural", "R$/kg", 0.5, 40, "Preço por quilo, usado quando a cotação é mássica.", 3, true),
  "gas.gnvPrecoMMBtu": n("Preço do gás natural", "R$/MMBtu", 5, 500, "Preço por milhão de BTU, base usual dos contratos industriais de gás.", 2, true),
  "gas.gnvPrecoIncluiIcms": b("Preço já inclui ICMS", "Quando desmarcado, o ICMS informado na aba Missão é acrescido ao preço."),
  "gas.gnvCustoLogisticoKg": n("Custo logístico adicional", "R$/kg", 0, 30, "Transporte de GNC em carreta até a base, quando não há rede de distribuição no local.", 2),
  "gas.gnvPerdasTransferenciaPct": p("Perdas de transferência", 0, 10, "Gás perdido na descarga e no abastecimento.", 2),

  "gas.bioModoSuprimento": s("Modo de suprimento do biometano", [{ value: "A", label: "A — Comprado de terceiro" }, { value: "B", label: "B — Produção própria a partir de biogás" }], "No modo A o biometano é comprado pronto. No modo B ele é produzido na própria operação, e o custo sai do CAPEX da planta, do substrato e do crédito do digestato."),
  "gas.bioMetodoPreco": s("Base de cotação — biometano", [{ value: "m3", label: "R$ por m³" }, { value: "kg", label: "R$ por kg" }, { value: "mmbtu", label: "R$ por MMBtu" }], "Base em que o contrato de compra do biometano é fechado."),
  "gas.bioPrecoM3": n("Preço do biometano", "R$/m³", 0.5, 30, "Preço por metro cúbico. Pode sair abaixo do gás natural quando o produtor monetiza CBIOs, ou acima quando há prêmio de certificação de origem.", 3, true),
  "gas.bioPrecoKg": n("Preço do biometano", "R$/kg", 0.5, 40, "Preço por quilo, usado quando a cotação é mássica.", 3, true),
  "gas.bioPrecoMMBtu": n("Preço do biometano", "R$/MMBtu", 5, 500, "Preço por milhão de BTU.", 2, true),
  "gas.bioPrecoIncluiIcms": b("Preço já inclui ICMS", "Quando desmarcado, o ICMS informado na aba Missão é acrescido ao preço."),
  "gas.bioCustoLogisticoKg": n("Custo logístico adicional", "R$/kg", 0, 30, "Transporte do biometano até a base, quando não há injeção na rede.", 2),
  "gas.bioPerdasTransferenciaPct": p("Perdas de transferência", 0, 10, "Biometano perdido na descarga e no abastecimento.", 2),
  "gas.bioPciKWhKg": n("Poder calorífico do biometano", "kWh/kg", 10, 16, "Biometano purificado é praticamente metano puro, com PCI de 13,9 kWh/kg — acima do gás natural. O motor precisa de menos quilos para a mesma missão, e o cálculo corrige isso automaticamente.", 2),
  "gas.bioDensidadeKgM3": n("Densidade do biometano", "kg/m³", 0.5, 1.2, "Densidade nas condições de faturamento. Metano puro a 20 °C e 1 atm: 0,716 kg/m³.", 3),
  "gas.bSubstratoTDia": n("Substrato processado", "t/dia", 1, 5000, "Dejetos, vinhaça, torta de filtro ou resíduo sólido alimentados ao biodigestor.", 0, true),
  "gas.bCustoSubstratoRSt": n("Custo do substrato", "R$/t", 0, 500, "Zero quando o resíduo é da própria operação. Informe o preço quando for comprado ou quando houver custo de transporte relevante.", 2),
  "gas.bRendimentoM3BiogasPorT": n("Rendimento em biogás", "m³/t de substrato", 5, 300, "Produção de biogás bruto por tonelada de substrato. Varia muito com o resíduo: dejeto bovino fica perto de 30 m³/t, vinhaça e resíduo alimentar chegam bem acima.", 1, true),
  "gas.bTeorMetanoPct": p("Teor de metano no biogás", 30, 80, "Percentual de metano no biogás bruto, antes da purificação. Faixa usual de 55% a 65%.", 1),
  "gas.bPerdaUpgradingPct": p("Perda no upgrading", 0, 20, "Metano perdido na purificação. Além do custo, essa perda é emissão direta de metano.", 2),
  "gas.bCapexPlanta": m("CAPEX da planta", 0, 1000000000, "Biodigestor, sistema de upgrading, compressão e conexão."),
  "gas.bOpexFixoPctAno": p("OPEX fixo", 0, 20, "Operação, manutenção e seguros, em % do CAPEX ao ano."),
  "gas.bOpexVariavelRSKg": n("OPEX variável", "R$/kg", 0, 20, "Energia, insumos e destinação, por quilo de biometano produzido.", 2),
  "gas.bVidaPlantaAnos": n("Vida da planta", "anos", 5, 40, "Prazo de amortização do CAPEX da planta.", 0),
  "gas.bCreditoDigestatoRSt": n("Crédito do digestato", "R$/t de substrato", 0, 500, "Receita do biofertilizante e economia de destinação do resíduo, por tonelada processada. Em muitas operações é esse crédito que torna o biometano competitivo.", 2, true),
});

/** Acesso seguro a um campo por caminho. */
export const getField = (path: string): FieldMeta =>
  FIELDS[path] ?? { label: path, unit: "", tip: "Campo sem metadado declarado.", kind: "num", dec: 2 };

/** Todos os caminhos numéricos, usados por solvers, tornado e Monte Carlo. */
export const NUMERIC_PATHS = Object.keys(FIELDS).filter((k) => {
  const f = FIELDS[k];
  return f.kind === "num" || f.kind === "pct" || f.kind === "money";
});
