// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqencctobyzozbyjiuqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxZW5jY3RvYnl6b3pieWppdXFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5ODQ5MjQsImV4cCI6MjA1MzU2MDkyNH0.SpfFp_CtXauNH0aqWQ93tizX2kCbubI-ns57U3F0Qsw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);